[versions]
agp = "8.13.0"
appcompat = "1.7.1"
activityCompose = "1.10.1"
composeBom = "2025.10.01"
constraintlayoutCompose = "1.1.1"
coreKtx = "1.17.0"
espressoCore = "3.7.0"
hiltAndroid = "2.57.1"
hiltNavigationCompose = "1.3.0"
junitJupiter = "5.13.4"
junitPlatformLauncher = "1.13.4"
kotest = "6.0.3"
kotlin = "2.2.20"
kotlin-ksp = "2.2.20-2.0.3"
junit = "4.13.2"
junitVersion = "1.3.0"
kotlinxCoroutinesTest = "1.10.2"
kotlinxSerializationJson = "1.9.0"
lifecycleRuntimeKtx = "2.9.3"
lifecycleViewmodelNav3 = "2.10.0"
material = "1.13.0"
mockk = "1.14.5"
nav3Core = "1.0.0"
navigationCompose = "2.9.5"
orbitMvi = "11.0.0"
turbine = "1.2.1"

[libraries]
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintlayoutCompose" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-navigation3 = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "lifecycleViewmodelNav3" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "nav3Core" }
androidx-navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "nav3Core" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltAndroid" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junitJupiter" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junitJupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junitPlatformLauncher" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
orbit-compose = { module = "org.orbit-mvi:orbit-compose", version.ref = "orbitMvi" }
orbit-core = { module = "org.orbit-mvi:orbit-core", version.ref = "orbitMvi" }
orbit-test = { module = "org.orbit-mvi:orbit-test", version.ref = "orbitMvi" }
orbit-viewmodel = { module = "org.orbit-mvi:orbit-viewmodel", version.ref = "orbitMvi" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

[bundles]
production-compose = [
    "androidx-activity-compose",
    "androidx-compose-bom",
    "androidx-compose-material3",
    "androidx-compose-ui",
    "androidx-compose-ui-graphics",
    "androidx-compose-ui-tooling-preview",
    "androidx-constraintlayout-compose",
    "androidx-hilt-navigation-compose",
]
debug-compose = [
    "androidx-compose-ui-tooling",
    "androidx-compose-ui-test-manifest"
]
orbit-production = [
    "orbit-compose",
    "orbit-core",
    "orbit-viewmodel",
]
orbit-test = [
    "orbit-test"
]
test-unit = [
    "junit-jupiter-api",
    "junit-platform-launcher",
    "kotest-assertions-core",
    "kotest-runner-junit5",
    "kotlinx-coroutines-test",
    "mockk",
    "turbine",
]
androidtest-common = [
    "androidx-compose-ui-test-junit4",
    "androidx-compose-ui-test-manifest",
    "junit",
]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin"}
kotlin-android = { id = "org.jetbrains.kotlin.android", version = "2.2.0" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "kotlin-ksp" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin"}
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hiltAndroid" }
